@ stdcall ArcticStartMenuToggle(long ptr long)
@ stdcall ArcticStartMenuHide()
@ stdcall ArcticStartMenuVisible()
@ stdcall ArcticStartMenuCustomize(long)
@ stdcall ArcticApplyTaskbarLook(long)
@ stdcall ArcticTaskbarLookPage(long)
@ stdcall ArcticApplyShellLook(long)
@ stdcall ArcticGetShellLook(ptr ptr ptr)
