"""Renders the kernel panic stop screen text into a C header for drm_panic.

usage: mkpanic.py <font.ttf> <out.h> [preview.png]

The kernel's own fonts have no Cyrillic, so the text is drawn here from
Noto Sans Light and stored as 4-bit alpha, run-length encoded:
  byte 0xVN with V != 0: N+1 pixels of alpha V
  bytes 0x0H 0xLL:       ((H << 8) | LL) + 1 transparent pixels
Two sizes: one for screens below 1000 lines, one for 1080p and up (4K
draws it doubled). The kernel writes the panic reason right after the
"what failed" label, at (what_x, what_y).
"""
import sys

from PIL import Image, ImageDraw, ImageFont

FACE = ":("
MESSAGE = "На вашому ПК виникла проблема, і його потрібно перезавантажити."
CODE = "Код зупинки: KERNEL_MODE_EXCEPTION_NOT_HANDLED"
WHAT = "Що спричинило збій:"

# (min screen height, face size, text size, small size, max text width)
SIZES = [(0, 120, 21, 12, 1000), (1000, 180, 30, 17, 1400)]


def wrap(font, text, max_width):
    lines, line = [], ""
    for word in text.split(" "):
        candidate = f"{line} {word}".strip()
        if line and font.getlength(candidate) > max_width:
            lines.append(line)
            line = word
        else:
            line = candidate
    return lines + [line]


def render(font_path, face_size, text_size, small_size, max_width):
    face = ImageFont.truetype(font_path, face_size)
    text = ImageFont.truetype(font_path, text_size)
    small = ImageFont.truetype(font_path, small_size)
    lines = wrap(text, MESSAGE, max_width)
    width = int(max([face.getlength(FACE)] + [text.getlength(l) for l in lines] +
                    [small.getlength(CODE), small.getlength(WHAT)])) + 4
    ops, y = [], 0

    def put(f, s, gap_after):
        nonlocal y
        ascent, descent = f.getmetrics()
        ops.append((f, s, y + ascent))
        y += int((ascent + descent) * gap_after)

    put(face, FACE, 1.2)
    for i, line in enumerate(lines):
        put(text, line, 1.25 if i < len(lines) - 1 else 2.2)
    put(small, CODE, 1.45)
    what_y = y
    what_x = int(small.getlength(WHAT + " "))
    put(small, WHAT, 1.45)
    height = y
    image = Image.new("L", (width, height), 0)
    draw = ImageDraw.Draw(image)
    for f, s, baseline in ops:
        draw.text((0, baseline), s, font=f, fill=255, anchor="ls")
    return image, what_x, what_y


def encode(image):
    pixels = [(a * 15 + 127) // 255 for a in image.tobytes()]
    out, i = bytearray(), 0
    while i < len(pixels):
        value, run = pixels[i], 1
        limit = 4096 if value == 0 else 16
        while i + run < len(pixels) and pixels[i + run] == value and run < limit:
            run += 1
        if value:
            out.append((value << 4) | (run - 1))
        else:
            out += bytes(((run - 1) >> 8, (run - 1) & 0xff))
        i += run
    return bytes(out)


font_path, out_path = sys.argv[1], sys.argv[2]
images, arrays, previews = [], [], []
for index, (min_height, face_size, text_size, small_size, max_width) in enumerate(SIZES):
    image, what_x, what_y = render(font_path, face_size, text_size, small_size, max_width)
    data = encode(image)
    body = ",".join(str(b) for b in data)
    arrays.append(f"static const u8 arctic_panic_rle{index}[] = {{{body}}};\n")
    images.append(f"\t{{ {min_height}, {image.width}, {image.height}, {what_x}, {what_y}, arctic_panic_rle{index} }},\n")
    previews.append(image)

with open(out_path, "w", encoding="utf-8") as out:
    out.write("/* SPDX-License-Identifier: GPL-2.0 OR MIT */\n")
    out.write("/* Generated by Project Arctic ci/mkpanic.py from Noto Sans Light. Do not edit. */\n\n")
    out.write("struct arctic_panic_image {\n\tunsigned int min_height, width, height, what_x, what_y;\n\tconst u8 *rle;\n};\n\n")
    out.writelines(arrays)
    out.write("\nstatic const struct arctic_panic_image arctic_panic_images[] = {\n")
    out.writelines(images)
    out.write("};\n")

if len(sys.argv) > 3:
    # the large image on a 1920x1080 screen, as the kernel lays it out
    screen = Image.new("RGB", (1920, 1080), (0, 0x78, 0xd7))
    white = Image.new("RGB", previews[1].size, (255, 255, 255))
    screen.paste(white, (1920 // 10, 1080 // 6), previews[1])
    screen.save(sys.argv[3])
