@ stdcall NPGetCaps(long)
@ stdcall NPOpenEnum(long long long ptr ptr)
@ stdcall NPEnumResource(ptr ptr ptr ptr)
@ stdcall NPCloseEnum(ptr)
@ stdcall NPGetResourceInformation(ptr ptr ptr ptr)
@ stdcall NPGetResourceParent(ptr ptr ptr)
@ stdcall NPAddConnection(ptr wstr wstr)
@ stdcall NPAddConnection3(ptr ptr wstr wstr long)
@ stdcall NPCancelConnection(wstr long)
@ stdcall NPGetConnection(wstr ptr ptr)
@ stdcall NPGetUser(wstr ptr ptr)
@ stdcall ConnectionDialog1W(ptr)
@ stdcall DisconnectDialog(ptr long)
@ stdcall RestoreConnectionsW(ptr ptr wstr long)
@ stdcall MapNetworkDriveW(ptr ptr wstr long)
@ stdcall DisconnectNetworkDrivesW(ptr ptr wstr long)
@ stdcall ForgetLogonsW(ptr ptr wstr long)
