"""Writes runtime/registry/filetypes.reg: the file types of Windows (.exe,
.bat, .txt, .dll, ...) as ReactOS registers them in boot/bootdata/hivecls.inf,
whose shell32 the shell is. Wine registers almost none of them: it runs an
.exe by itself, but the shell needs .exe -> exefile for the icon and "Open".

Taken: the extensions, the types they point at and the shell's own classes
(*, Folder, Directory, Drive...: Wine has no Folder, so a folder had no
"Open" and Enter opened its properties). Not CLSIDs, which stay Wine's.

usage (in WSL, on the ReactOS tree): python3 tools/hivecls2reg.py HIVECLS.INF OUT.REG
"""
import re
import sys

src, dst = sys.argv[1], sys.argv[2]
text = open(src, encoding="utf-8-sig", errors="replace").read()

# [Strings] for %NAME% values
strings = {}
section = None
for line in text.splitlines():
    s = line.strip()
    if s.startswith("["):
        section = s.strip("[]").lower()
        continue
    if section == "strings" and "=" in s and not s.startswith(";"):
        k, v = s.split("=", 1)
        strings[k.strip().lower()] = v.strip().strip('"')


def fields(line):
    """splits an INF line on commas outside quotes"""
    out, cur, q = [], "", False
    i = 0
    while i < len(line):
        c = line[i]
        if c == '"':
            if q and i + 1 < len(line) and line[i + 1] == '"':
                cur += '"'
                i += 2
                continue
            q = not q
        elif c == "," and not q:
            out.append(cur.strip())
            cur = ""
        elif c == ";" and not q:
            break
        else:
            cur += c
        i += 1
    out.append(cur.strip())
    return out


def subst(v):
    return re.sub(r"%(\w+)%", lambda m: strings.get(m.group(1).lower(), m.group(0)), v)


entries = []
for line in text.splitlines():
    if not line.startswith("HKCR,"):
        continue
    f = fields(line)
    while len(f) < 5:
        f.append("")
    key, name, flags, data = f[1], f[2], f[3], ",".join(f[4:]) if len(f) > 5 else f[4]
    flags = int(flags, 0) if flags else 0
    entries.append((key, name, flags, subst(data)))

exts = {k for k, n, fl, d in entries if re.match(r"^\.[^\\]+$", k)}
progids = {d for k, n, fl, d in entries if k in exts and n == "" and d and not d.startswith("{")}


# the shell's own classes: what every file, folder and drive can do
BASE = {"*", "Folder", "Directory", "Drive", "Unknown", "SystemFileAssociations", "MIME"}


def wanted(key):
    top = key.split("\\", 1)[0]
    return top in exts or top in progids or top in BASE


def reg_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def reg_value(flags, data):
    typ = flags & 0xFFFF0001
    if flags & 0x10:  # FLG_ADDREG_KEYONLY
        return None
    if typ == 0x00010001:  # REG_DWORD
        return "dword:%08x" % (int(data, 0) if data else 0)
    if typ == 0x00020000:  # REG_EXPAND_SZ
        raw = (data + "\0").encode("utf-16-le")
        return "hex(2):" + ",".join("%02x" % b for b in raw)
    if typ == 0x00000001:  # REG_BINARY
        return "hex:" + ",".join(b.strip().lower() for b in data.split(",") if b.strip())
    if typ == 0x00010000:  # REG_MULTI_SZ
        raw = (data + "\0\0").encode("utf-16-le")
        return "hex(7):" + ",".join("%02x" % b for b in raw)
    return '"%s"' % reg_escape(data)


keys = {}
for key, name, flags, data in entries:
    if not wanted(key):
        continue
    # the system is Windows here, as the shell calls it
    data = data.replace("ReactOS", "Windows")
    keys.setdefault(key, [])
    v = reg_value(flags, data)
    if v is not None:
        keys[key].append(('@' if name == "" else '"%s"' % reg_escape(name), v))

with open(dst, "w", encoding="utf-16", newline="\r\n") as out:
    out.write("Windows Registry Editor Version 5.00\n\n")
    out.write("; Generated by tools/hivecls2reg.py from ReactOS boot/bootdata/hivecls.inf\n\n")
    for key in sorted(keys, key=str.lower):
        out.write("[HKEY_LOCAL_MACHINE\\Software\\Classes\\%s]\n" % key)
        for name, v in keys[key]:
            out.write("%s=%s\n" % (name, v))
        out.write("\n")
print("%d extensions, %d types, %d keys" % (len(exts), len(progids), len(keys)))
