#if 0
#pragma makedep unix
#endif

/* Generated by wayland-scanner 1.26.0 */

/*
 * Copyright Project Arctic contributors.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include <wayland-util.h>

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface arctic_configuration_v1_interface;
extern const struct wl_interface arctic_output_v1_interface;
extern const struct wl_interface wl_output_interface;

static const struct wl_interface *arctic_display_v1_types[] = {
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	&arctic_output_v1_interface,
	&wl_output_interface,
	&arctic_configuration_v1_interface,
	&wl_output_interface,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
};

static const struct wl_message arctic_display_v1_requests[] = {
	{ "destroy", "", arctic_display_v1_types + 0 },
	{ "get_output", "no", arctic_display_v1_types + 5 },
	{ "create_configuration", "n", arctic_display_v1_types + 7 },
};

static const struct wl_message arctic_display_v1_events[] = {
	{ "adapter", "uuuus", arctic_display_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface arctic_display_v1_interface = {
	"arctic_display_v1", 1,
	3, arctic_display_v1_requests,
	1, arctic_display_v1_events,
};

static const struct wl_message arctic_output_v1_requests[] = {
	{ "destroy", "", arctic_display_v1_types + 0 },
};

static const struct wl_message arctic_output_v1_events[] = {
	{ "edid", "a", arctic_display_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface arctic_output_v1_interface = {
	"arctic_output_v1", 1,
	1, arctic_output_v1_requests,
	1, arctic_output_v1_events,
};

static const struct wl_message arctic_configuration_v1_requests[] = {
	{ "destroy", "", arctic_display_v1_types + 0 },
	{ "set_mode", "oiiiii", arctic_display_v1_types + 8 },
	{ "apply", "u", arctic_display_v1_types + 0 },
};

static const struct wl_message arctic_configuration_v1_events[] = {
	{ "succeeded", "", arctic_display_v1_types + 0 },
	{ "failed", "", arctic_display_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface arctic_configuration_v1_interface = {
	"arctic_configuration_v1", 1,
	3, arctic_configuration_v1_requests,
	2, arctic_configuration_v1_events,
};

