/* Generated by wayland-scanner 1.26.0 */

/*
 * Copyright Project Arctic contributors.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface arctic_window_v1_interface;
extern const struct wl_interface wl_buffer_interface;
extern const struct wl_interface wl_surface_interface;

static const struct wl_interface *arctic_shell_v1_types[] = {
	&arctic_window_v1_interface,
	&wl_surface_interface,
	NULL,
	&wl_buffer_interface,
	NULL,
	NULL,
	NULL,
};

static const struct wl_message arctic_shell_v1_requests[] = {
	{ "destroy", "", arctic_shell_v1_types + 0 },
	{ "get_window", "nou", arctic_shell_v1_types + 0 },
	{ "set_cursor", "2?oiiu", arctic_shell_v1_types + 3 },
};

WL_PRIVATE const struct wl_interface arctic_shell_v1_interface = {
	"arctic_shell_v1", 2,
	3, arctic_shell_v1_requests,
	0, NULL,
};

static const struct wl_message arctic_window_v1_requests[] = {
	{ "destroy", "", arctic_shell_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface arctic_window_v1_interface = {
	"arctic_window_v1", 1,
	1, arctic_window_v1_requests,
	0, NULL,
};

