/* Generated by wayland-scanner 1.26.0 */

#ifndef ARCTIC_SHELL_V1_SERVER_PROTOCOL_H
#define ARCTIC_SHELL_V1_SERVER_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-server.h"

#ifdef  __cplusplus
extern "C" {
#endif

struct wl_client;
struct wl_resource;

/**
 * @page page_arctic_shell_v1 The arctic_shell_v1 protocol
 * @section page_ifaces_arctic_shell_v1 Interfaces
 * - @subpage page_iface_arctic_shell_v1 - ties surfaces to Win32 windows
 * - @subpage page_iface_arctic_window_v1 - a surface that shows a Win32 window
 * @section page_copyright_arctic_shell_v1 Copyright
 * <pre>
 *
 * Copyright Project Arctic contributors.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * </pre>
 */
struct arctic_shell_v1;
struct arctic_window_v1;
struct wl_buffer;
struct wl_surface;

#ifndef ARCTIC_SHELL_V1_INTERFACE
#define ARCTIC_SHELL_V1_INTERFACE
/**
 * @page page_iface_arctic_shell_v1 arctic_shell_v1
 * @section page_iface_arctic_shell_v1_desc Description
 *
 * Offered by dwm.exe. A client only says which Win32 window a surface
 * shows. Where windows are, which are visible and how they are stacked,
 * dwm.exe reads from wineserver itself, never from the client.
 * @section page_iface_arctic_shell_v1_api API
 * See @ref iface_arctic_shell_v1.
 */
/**
 * @defgroup iface_arctic_shell_v1 The arctic_shell_v1 interface
 *
 * Offered by dwm.exe. A client only says which Win32 window a surface
 * shows. Where windows are, which are visible and how they are stacked,
 * dwm.exe reads from wineserver itself, never from the client.
 */
extern const struct wl_interface arctic_shell_v1_interface;
#endif
#ifndef ARCTIC_WINDOW_V1_INTERFACE
#define ARCTIC_WINDOW_V1_INTERFACE
/**
 * @page page_iface_arctic_window_v1 arctic_window_v1
 * @section page_iface_arctic_window_v1_desc Description
 * @section page_iface_arctic_window_v1_api API
 * See @ref iface_arctic_window_v1.
 */
/**
 * @defgroup iface_arctic_window_v1 The arctic_window_v1 interface
 */
extern const struct wl_interface arctic_window_v1_interface;
#endif

/**
 * @ingroup iface_arctic_shell_v1
 * @struct arctic_shell_v1_interface
 */
struct arctic_shell_v1_interface {
	/**
	 */
	void (*destroy)(struct wl_client *client,
			struct wl_resource *resource);
	/**
	 * @param hwnd window handle, as wineserver knows it
	 */
	void (*get_window)(struct wl_client *client,
			   struct wl_resource *resource,
			   uint32_t id,
			   struct wl_resource *surface,
			   uint32_t hwnd);
	/**
	 * the pointer over this client's windows
	 *
	 * Sent by the process whose window is under the pointer when its
	 * cursor changes (WM_WINE_SETCURSOR). dwm.exe draws the standard
	 * arrow itself at the monitor's scale; any other cursor comes as
	 * its image, premultiplied ARGB, which dwm.exe copies at once. No
	 * buffer and no arrow: the cursor is hidden.
	 * @param arrow 1: the standard arrow
	 * @since 2
	 */
	void (*set_cursor)(struct wl_client *client,
			   struct wl_resource *resource,
			   struct wl_resource *buffer,
			   int32_t hotspot_x,
			   int32_t hotspot_y,
			   uint32_t arrow);
};


/**
 * @ingroup iface_arctic_shell_v1
 */
#define ARCTIC_SHELL_V1_DESTROY_SINCE_VERSION 1
/**
 * @ingroup iface_arctic_shell_v1
 */
#define ARCTIC_SHELL_V1_GET_WINDOW_SINCE_VERSION 1
/**
 * @ingroup iface_arctic_shell_v1
 */
#define ARCTIC_SHELL_V1_SET_CURSOR_SINCE_VERSION 2

/**
 * @ingroup iface_arctic_window_v1
 * @struct arctic_window_v1_interface
 */
struct arctic_window_v1_interface {
	/**
	 */
	void (*destroy)(struct wl_client *client,
			struct wl_resource *resource);
};


/**
 * @ingroup iface_arctic_window_v1
 */
#define ARCTIC_WINDOW_V1_DESTROY_SINCE_VERSION 1

#ifdef  __cplusplus
}
#endif

#endif
