/* Generated by wayland-scanner 1.26.0 */

#ifndef ARCTIC_DISPLAY_V1_SERVER_PROTOCOL_H
#define ARCTIC_DISPLAY_V1_SERVER_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include <wayland-server.h>

#ifdef  __cplusplus
extern "C" {
#endif

struct wl_client;
struct wl_resource;

/**
 * @page page_arctic_display_v1 The arctic_display_v1 protocol
 * @section page_ifaces_arctic_display_v1 Interfaces
 * - @subpage page_iface_arctic_display_v1 - the display hardware behind the outputs
 * - @subpage page_iface_arctic_output_v1 - what an output is connected to
 * - @subpage page_iface_arctic_configuration_v1 - modes and positions for the outputs, applied at once
 * @section page_copyright_arctic_display_v1 Copyright
 * <pre>
 *
 * Copyright Project Arctic contributors.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * </pre>
 */
struct arctic_configuration_v1;
struct arctic_display_v1;
struct arctic_output_v1;
struct wl_output;

#ifndef ARCTIC_DISPLAY_V1_INTERFACE
#define ARCTIC_DISPLAY_V1_INTERFACE
/**
 * @page page_iface_arctic_display_v1 arctic_display_v1
 * @section page_iface_arctic_display_v1_desc Description
 *
 * Offered by dwm.exe next to wl_output and xdg_output: the graphics
 * adapter, the EDID of each output, and mode setting. The modes are the
 * ones wl_output advertises; the display layout of the Win32 world is
 * applied through a configuration.
 * @section page_iface_arctic_display_v1_api API
 * See @ref iface_arctic_display_v1.
 */
/**
 * @defgroup iface_arctic_display_v1 The arctic_display_v1 interface
 *
 * Offered by dwm.exe next to wl_output and xdg_output: the graphics
 * adapter, the EDID of each output, and mode setting. The modes are the
 * ones wl_output advertises; the display layout of the Win32 world is
 * applied through a configuration.
 */
extern const struct wl_interface arctic_display_v1_interface;
#endif
#ifndef ARCTIC_OUTPUT_V1_INTERFACE
#define ARCTIC_OUTPUT_V1_INTERFACE
/**
 * @page page_iface_arctic_output_v1 arctic_output_v1
 * @section page_iface_arctic_output_v1_desc Description
 * @section page_iface_arctic_output_v1_api API
 * See @ref iface_arctic_output_v1.
 */
/**
 * @defgroup iface_arctic_output_v1 The arctic_output_v1 interface
 */
extern const struct wl_interface arctic_output_v1_interface;
#endif
#ifndef ARCTIC_CONFIGURATION_V1_INTERFACE
#define ARCTIC_CONFIGURATION_V1_INTERFACE
/**
 * @page page_iface_arctic_configuration_v1 arctic_configuration_v1
 * @section page_iface_arctic_configuration_v1_desc Description
 *
 * Outputs the configuration does not name keep their mode and position.
 * On apply dwm.exe answers with succeeded or failed; either way the
 * configuration is used up and the client destroys it. Before
 * succeeded, every wl_output that changed has sent its new mode and
 * position.
 * @section page_iface_arctic_configuration_v1_api API
 * See @ref iface_arctic_configuration_v1.
 */
/**
 * @defgroup iface_arctic_configuration_v1 The arctic_configuration_v1 interface
 *
 * Outputs the configuration does not name keep their mode and position.
 * On apply dwm.exe answers with succeeded or failed; either way the
 * configuration is used up and the client destroys it. Before
 * succeeded, every wl_output that changed has sent its new mode and
 * position.
 */
extern const struct wl_interface arctic_configuration_v1_interface;
#endif

/**
 * @ingroup iface_arctic_display_v1
 * @struct arctic_display_v1_interface
 */
struct arctic_display_v1_interface {
	/**
	 */
	void (*destroy)(struct wl_client *client,
			struct wl_resource *resource);
	/**
	 */
	void (*get_output)(struct wl_client *client,
			   struct wl_resource *resource,
			   uint32_t id,
			   struct wl_resource *output);
	/**
	 */
	void (*create_configuration)(struct wl_client *client,
				     struct wl_resource *resource,
				     uint32_t id);
};

#define ARCTIC_DISPLAY_V1_ADAPTER 0

/**
 * @ingroup iface_arctic_display_v1
 */
#define ARCTIC_DISPLAY_V1_ADAPTER_SINCE_VERSION 1

/**
 * @ingroup iface_arctic_display_v1
 */
#define ARCTIC_DISPLAY_V1_DESTROY_SINCE_VERSION 1
/**
 * @ingroup iface_arctic_display_v1
 */
#define ARCTIC_DISPLAY_V1_GET_OUTPUT_SINCE_VERSION 1
/**
 * @ingroup iface_arctic_display_v1
 */
#define ARCTIC_DISPLAY_V1_CREATE_CONFIGURATION_SINCE_VERSION 1

/**
 * @ingroup iface_arctic_display_v1
 * Sends an adapter event to the client owning the resource.
 * @param resource_ The client's resource
 */
static inline void
arctic_display_v1_send_adapter(struct wl_resource *resource_, uint32_t vendor, uint32_t device, uint32_t subsystem, uint32_t revision, const char *description)
{
	wl_resource_post_event(resource_, ARCTIC_DISPLAY_V1_ADAPTER, vendor, device, subsystem, revision, description);
}

/**
 * @ingroup iface_arctic_output_v1
 * @struct arctic_output_v1_interface
 */
struct arctic_output_v1_interface {
	/**
	 */
	void (*destroy)(struct wl_client *client,
			struct wl_resource *resource);
};

#define ARCTIC_OUTPUT_V1_EDID 0

/**
 * @ingroup iface_arctic_output_v1
 */
#define ARCTIC_OUTPUT_V1_EDID_SINCE_VERSION 1

/**
 * @ingroup iface_arctic_output_v1
 */
#define ARCTIC_OUTPUT_V1_DESTROY_SINCE_VERSION 1

/**
 * @ingroup iface_arctic_output_v1
 * Sends an edid event to the client owning the resource.
 * @param resource_ The client's resource
 */
static inline void
arctic_output_v1_send_edid(struct wl_resource *resource_, struct wl_array *edid)
{
	wl_resource_post_event(resource_, ARCTIC_OUTPUT_V1_EDID, edid);
}

#ifndef ARCTIC_CONFIGURATION_V1_APPLY_FLAGS_ENUM
#define ARCTIC_CONFIGURATION_V1_APPLY_FLAGS_ENUM
enum arctic_configuration_v1_apply_flags {
	/**
	 * only check that the configuration can be shown
	 */
	ARCTIC_CONFIGURATION_V1_APPLY_FLAGS_TEST = 1,
	/**
	 * keep it for this set of monitors, across restarts
	 */
	ARCTIC_CONFIGURATION_V1_APPLY_FLAGS_PERSIST = 2,
};
#endif /* ARCTIC_CONFIGURATION_V1_APPLY_FLAGS_ENUM */

#ifndef ARCTIC_CONFIGURATION_V1_APPLY_FLAGS_ENUM_IS_VALID
#define ARCTIC_CONFIGURATION_V1_APPLY_FLAGS_ENUM_IS_VALID
/**
 * @ingroup iface_arctic_configuration_v1
 * Validate a arctic_configuration_v1 apply_flags value.
 *
 * @return true on success, false on error.
 * @ref arctic_configuration_v1_apply_flags
 */
static inline bool
arctic_configuration_v1_apply_flags_is_valid(uint32_t value, uint32_t version) {
	uint32_t valid = 0;
	if (version >= 1)
		valid |= ARCTIC_CONFIGURATION_V1_APPLY_FLAGS_TEST;
	if (version >= 1)
		valid |= ARCTIC_CONFIGURATION_V1_APPLY_FLAGS_PERSIST;
	return (value & ~valid) == 0;
}
#endif /* ARCTIC_CONFIGURATION_V1_APPLY_FLAGS_ENUM_IS_VALID */

/**
 * @ingroup iface_arctic_configuration_v1
 * @struct arctic_configuration_v1_interface
 */
struct arctic_configuration_v1_interface {
	/**
	 */
	void (*destroy)(struct wl_client *client,
			struct wl_resource *resource);
	/**
	 * @param x position in the virtual screen
	 * @param refresh mHz, as the wl_output mode event gave it
	 */
	void (*set_mode)(struct wl_client *client,
			 struct wl_resource *resource,
			 struct wl_resource *output,
			 int32_t x,
			 int32_t y,
			 int32_t width,
			 int32_t height,
			 int32_t refresh);
	/**
	 */
	void (*apply)(struct wl_client *client,
		      struct wl_resource *resource,
		      uint32_t flags);
};

#define ARCTIC_CONFIGURATION_V1_SUCCEEDED 0
#define ARCTIC_CONFIGURATION_V1_FAILED 1

/**
 * @ingroup iface_arctic_configuration_v1
 */
#define ARCTIC_CONFIGURATION_V1_SUCCEEDED_SINCE_VERSION 1
/**
 * @ingroup iface_arctic_configuration_v1
 */
#define ARCTIC_CONFIGURATION_V1_FAILED_SINCE_VERSION 1

/**
 * @ingroup iface_arctic_configuration_v1
 */
#define ARCTIC_CONFIGURATION_V1_DESTROY_SINCE_VERSION 1
/**
 * @ingroup iface_arctic_configuration_v1
 */
#define ARCTIC_CONFIGURATION_V1_SET_MODE_SINCE_VERSION 1
/**
 * @ingroup iface_arctic_configuration_v1
 */
#define ARCTIC_CONFIGURATION_V1_APPLY_SINCE_VERSION 1

/**
 * @ingroup iface_arctic_configuration_v1
 * Sends an succeeded event to the client owning the resource.
 * @param resource_ The client's resource
 */
static inline void
arctic_configuration_v1_send_succeeded(struct wl_resource *resource_)
{
	wl_resource_post_event(resource_, ARCTIC_CONFIGURATION_V1_SUCCEEDED);
}

/**
 * @ingroup iface_arctic_configuration_v1
 * Sends an failed event to the client owning the resource.
 * @param resource_ The client's resource
 */
static inline void
arctic_configuration_v1_send_failed(struct wl_resource *resource_)
{
	wl_resource_post_event(resource_, ARCTIC_CONFIGURATION_V1_FAILED);
}

#ifdef  __cplusplus
}
#endif

#endif
