timeout: 0
quiet: yes

/Arctic
    protocol: linux
    path: boot():/arctic/vmlinuz
    module_path: boot():/arctic/initrd.img
    cmdline: console=ttyS0,115200 loglevel=6 log_buf_len=4M arctic.dev=1
