@ stdcall CallNtPowerInformation (long ptr long ptr long)
@ stdcall CanUserWritePwrScheme ()
@ stdcall DeletePwrScheme (long)
@ stdcall EnumPwrSchemes (ptr long)
@ stdcall GetActivePwrScheme (ptr)
@ stdcall GetCurrentPowerPolicies (ptr ptr)
@ stdcall GetPwrCapabilities (ptr)
@ stdcall GetPwrDiskSpindownRange (ptr ptr)
@ stdcall IsAdminOverrideActive (ptr)
@ stdcall IsPwrHibernateAllowed ()
@ stdcall IsPwrShutdownAllowed ()
@ stdcall IsPwrSuspendAllowed ()
@ stdcall PowerCanRestoreIndividualDefaultPowerScheme(ptr)
@ stdcall PowerDeleteScheme(ptr ptr)
@ stdcall PowerDeterminePlatformRole ()
@ stdcall PowerDeterminePlatformRoleEx(long)
@ stdcall PowerDuplicateScheme(ptr ptr ptr)
@ stdcall PowerEnumerate(long ptr ptr long long ptr ptr)
@ stdcall PowerGetActiveScheme (ptr ptr)
@ stdcall PowerGetActualOverlayScheme(ptr)
@ stdcall PowerGetEffectiveOverlayScheme(ptr)
@ stdcall PowerGetOverlaySchemes(ptr ptr long)
@ stdcall PowerReadACDefaultIndex(ptr ptr ptr ptr ptr)
@ stdcall PowerReadACValue(ptr ptr ptr ptr ptr ptr ptr)
@ stdcall PowerReadACValueIndex(ptr ptr ptr ptr ptr)
@ stdcall PowerReadDCDefaultIndex(ptr ptr ptr ptr ptr)
@ stdcall PowerReadDCValue (ptr ptr ptr ptr ptr ptr ptr)
@ stdcall PowerReadDCValueIndex(ptr ptr ptr ptr ptr)
@ stdcall PowerReadDescription(ptr ptr ptr ptr ptr ptr)
@ stdcall PowerReadFriendlyName (ptr ptr ptr ptr ptr ptr)
@ stdcall PowerReadPossibleDescription(ptr ptr ptr long ptr ptr)
@ stdcall PowerReadPossibleFriendlyName(ptr ptr ptr long ptr ptr)
@ stdcall PowerReadPossibleValue(ptr ptr ptr ptr long ptr ptr)
@ stdcall PowerReadSettingAttributes(ptr ptr)
@ stdcall PowerReadValueIncrement(ptr ptr ptr ptr)
@ stdcall PowerReadValueMax(ptr ptr ptr ptr)
@ stdcall PowerReadValueMin(ptr ptr ptr ptr)
@ stdcall PowerReadValueUnitsSpecifier(ptr ptr ptr ptr ptr)
@ stdcall PowerRegisterForEffectivePowerModeNotifications(long ptr ptr ptr)
@ stdcall PowerRegisterSuspendResumeNotification(long ptr ptr)
@ stdcall PowerRestoreDefaultPowerSchemes()
@ stdcall PowerRestoreIndividualDefaultPowerScheme(ptr)
@ stdcall PowerSetActiveOverlayScheme(ptr)
@ stdcall PowerSetActiveScheme (ptr ptr)
@ stdcall PowerSettingAccessCheck(long ptr)
@ stdcall PowerSettingAccessCheckEx(long ptr long)
@ stdcall PowerSettingRegisterNotification(ptr long ptr ptr)
@ stdcall PowerSettingUnregisterNotification(ptr)
@ stdcall PowerUnregisterFromEffectivePowerModeNotifications(ptr)
@ stdcall PowerUnregisterSuspendResumeNotification(ptr)
@ stdcall PowerWriteACValueIndex(ptr ptr ptr ptr long)
@ stdcall PowerWriteDCValueIndex(ptr ptr ptr ptr long)
@ stdcall PowerWriteDescription(ptr ptr ptr ptr ptr long)
@ stdcall PowerWriteFriendlyName(ptr ptr ptr ptr ptr long)
@ stdcall PowerWriteSettingAttributes(ptr ptr long)
@ stdcall ReadGlobalPwrPolicy (ptr)
@ stdcall ReadProcessorPwrScheme (long ptr)
@ stdcall ReadPwrScheme (long ptr)
@ stdcall SetActivePwrScheme (long ptr ptr)
@ stdcall SetSuspendState (long long long)
@ stdcall WriteGlobalPwrPolicy (ptr)
@ stdcall WriteProcessorPwrScheme (long ptr)
@ stdcall WritePwrScheme (ptr str str ptr)

# Arctic (wine/arctic_power.h)
@ stdcall ArcticCpuInfo(ptr)
@ stdcall ArcticGpuList(ptr long)
@ stdcall ArcticGpuPublish()
@ stdcall ArcticPowerApply(ptr)
@ stdcall ArcticPowerRequest(str)
@ stdcall ArcticPowerStatus(ptr)
